### ISSUE TITLE
`/mola/demos` parameters outdated

### ISSUE THREAD

**Issue by TankPi** [MOLAorg/mola-fe-lidar#1]
When I try to run the demo `Demo: Velodyne dataset in Rawlog format, 3D-LiDAR SLAM`, I get following error:

![Screenshot from 2021-03-22 12-15-29](https://user-images.githubusercontent.com/11289683/111981747-5fe87080-8b08-11eb-87a8-39e6ad37dc22.png)

When I look at the [`rawlog_odom_and_lidar.yml` ](https://github.com/MOLAorg/mola/blob/master/demos/rawlog_odom_and_lidar.yml#L114) line 114:

```yaml
icp_params_with_vel.maxIterations:  10    90
icp_params_with_vel.thresholdDist:   1.0   0.50   # [meters]
icp_params_with_vel.thresholdAng:    2.0   0.01   # [deg]
# Case: WITHOUT a good twist (velocity) model:
icp_params_without_vel.maxIterations:   5     100
icp_params_without_vel.thresholdDist:   3.0   0.50  # [meters]
icp_params_without_vel.thresholdAng:    2.0   0.01  # [deg]
# Case: Loop closure
loop_closure_montecarlo_samples: 10
icp_params_loopclosure.maxIterations: 10    40    90
icp_params_loopclosure.thresholdDist: 30.0  5.0  0.50  # [meters]
icp_params_loopclosure.thresholdAng:   2.0  0.5  0.01  # [deg]
```

Is correct that this as to be refactored to `icp_settings_with_vel`? Simply changing `icp_params` to `icp_settings` does not resolve the issue. I've also tried `mola/demos/ros1_velodyne_slam.yml`,  this gives the same issue.
